version: '3' # composeファイルのバージョン
services:
  go-websocket-with-docker: # サービス名
    container_name: go-websocket-with-docker
    build: # ビルドに使うDockerファイルのパス
      context: .
      dockerfile: ./build/Dockerfile
    volumes: # マウントディレクトリ
      - ./go-websocket:/go/src/github.com/go-websocket-with-docker
    tty: true # コンテナの永続化
    env_file: # .envファイル
      - ./build/.go_env
    environment:
      - TZ=Asia/Tokyo
    ports:
      - 9000:9000